### ISSUE TITLE
ideas

### ISSUE THREAD

**Issue by ghost** [dc0d/dockage#9]
its Damien Katz's original Relax / Couch DB reinvented ?

https://www.slideshare.net/karmi/couchdb-a-database-for-the-web

I think today a P2P db really needs CRDT. Its so useful. Its being baked into many new Os's even. See Fuchsia Ledger.

I tried to convert automerge to golang, but only got 10% there. no time.
There are a few others out there but they are mostly incomplete.

--

The other thing is Flatbuffers. Its basically a db and network protocol in one. Very fast and powerful.
Here is a high level example of what i mean:
https://github.com/urban-wombat
Its pretty cool but is still raw

**Comment by dc0d** [comment]
Not really, and this is not comparable to a full fledged database like CouchDB. The only part got from CouchDB is the idea of having views as secondary indexes.

I am not database designer. This is my first attempt and it is intended to be an embedded database - like SQLite. So supporting distributed features is not a goal.

The motive here was that I got frustrated by the status of embedded databases in Go world (I have examined most of them).

Indeed I had this ambitious goal of writing a CouchDB-Compatible database (like PouchDB), but I learnt it is not a one man endeavor. Besides, what I need right now is a flexible, reliable embedded NoSQL in pure Go!

**Comment by ghost** [comment]
that what urban wombat is ! Its a embedded db using pure flat buffers
Its just more abstract than boltdb etc etc etc.

**Comment by dc0d** [comment]
Interesting! Never heard of it. Yet:

- It is design for only tabular data - not nested data structures as it occurs in JSON (and app logic).
- It is designed for keeping small chunks of data - like configuration.
- It has very limited query capabilities.

**Comment by ghost** [comment]
Your right on your first assertion
Totally wrong on the 2nd. If you had a 1 terrabyte Flatbuffers file you can read a part of it at the file is layer. You can read it as the whole 1 terrabyte was being streamed to you over a network.

3rd point is true but code gen fixes that.

The problem of tabular data is not really a problem. A CQRS architecture stores the readable data as a denormalise tree - i.e a table.
That's really what you want for a proper system. The write side are mutation actions that hit the data plane and all the relevant read only repos subscribe to certain mutation topics and update them selves.
This cqrs style of mvvm is not for everyone

**Comment by dc0d** [comment]
I am not familiar with FlatBuffers that much. AFAIK it is like ProtoBuff (or any other serialization format) and has nothing to do with a storage layer in a database.

I have asked the same question from themselves (https://github.com/urban-wombat/gotables/issues/7).
